# Generated by Django 5.2.1 on 2025-06-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactTable',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=256)),
                ('phoneC', models.CharField(max_length=50)),
                ('emailC', models.EmailField(max_length=254)),
                ('isClient', models.BooleanField()),
            ],
        ),
    ]
